### ISSUE TITLE
'At a glance' information

### ISSUE THREAD

**Issue by TehChozinOne** [ForzaMods/Forza-Mods-AIO#10]
Since most of the options are now combined, AIO should show toggle position somewhere. Could be something like this..

![Discord_FytvLfiVK6](https://github.com/ForzaMods/Forza-Mods-AIO/assets/20630725/94df0019-3bba-41c6-8849-d46f59696984)

**Comment by szaaamerik** [comment]
added to the mvvm port.
![image](https://github.com/ForzaMods/Forza-Mods-AIO/assets/126014478/1bd26347-ab3c-40c6-b444-98a32ff2a232)
