### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by KashifXain** [ForzaMods/Forza-Mods-AIO#102]
### Which version of the app?

latest AIO version

### Description

Address for this feature could not found 
try to activate the cheat engine or try to restart cheat engine or forza horizen 5

### Screenshots

![Forza Mods AIO 7_27_2024 9_18_18 AM](https://github.com/user-attachments/assets/25c7e1e7-f522-4e0a-b0c2-cf5eebfe9d5c)

### Windows version

Windows 11 21H2 (22000)

**Comment by szaaamerik** [comment]
update your game. I'm not going out my way to natively support the launch release
