### ISSUE TITLE
Customize the car

### ISSUE THREAD

**Issue by Miguel13000** [ForzaMods/Forza-Mods-AIO#107]
### Description

Hello I have an excellent idea, in forzavista it is possible to remove the engine window on certain cars and it would be nice to have the possibility of doing it in gameplay a very good example: The Ferrari Corse Clienti #25 which gives a monstrous result I don't know if it's possible but thank you in advance.

### Screenshots

![20240816162048_1](https://github.com/user-attachments/assets/9728597c-293c-4085-a854-f5907801deb3)

**Comment by szaaamerik** [comment]
Not planned.
