### ISSUE TITLE
Got A Ban

### ISSUE THREAD

**Issue by zoomduh** [ForzaMods/Forza-Mods-AIO#109]
### Which version of the app?

2.4.0.1

### Description

EDIT: Hopped in a week later and I'm unbanned for some reason. idk if this will last thoo.

Got banned from online after like 2 days of getting a few rare cars which I made them available in the AutoShow.
I also tried [FH5RP](https://github.com/jaaiden/FH5RP) for a couple of minutes but I don't thinks it's the reason for the ban, is it?

### Screenshots

![image](https://github.com/user-attachments/assets/ead9ff8f-f1bf-4cea-a656-55f651d061c4)

### Windows version

Windows 11 22H2 (22621)

**Comment by szaaamerik** [comment]
Not a bug. In all of our release notes we clearly state were not responsible for any bans.

**Comment by zoomduh** [comment]
> Not a bug. In all of our release notes we clearly state were not responsible for any bans.

Yeah I know.
I've used this app like 10 months ago to get credits/cars and and it was so worth it. Maybe I got a little too excited adding a punch of rare cars at once, I'm asking if this what got me banned, Which seems so.
Screw the online anyways and thanks for making this goated app.
