### ISSUE TITLE
some cars are missing please update

### ISSUE THREAD

**Issue by gotstoned9** [ForzaMods/Forza-Mods-AIO#11]
there are some cars missing when using All Cars,
Potiac firebird trans am 1970
Audi ID,4
etc

looking forward your update

thanks

**Comment by cmcalsdr** [comment]
how do i open the garage and autoshow tab it doesnt let me

**Comment by szaaamerik** [comment]
> there are some cars missing when using All Cars, Potiac firebird trans am 1970 Audi ID,4 etc
> 
> looking forward your update
> 
> thanks


no they arent. update your game.


![image](https://github.com/ForzaMods/Forza-Mods-AIO/assets/126014478/01c56de8-679e-4885-900b-3802b46ceefd)
![image](https://github.com/ForzaMods/Forza-Mods-AIO/assets/126014478/02474a00-8b79-4f1c-a5c2-1b13564176f6)




> how do i open the garage and autoshow tab it doesnt let me


launch the aio as admin.

**Comment by gotstoned9** [comment]
> > there are some cars missing when using All Cars, Potiac firebird trans am 1970 Audi ID,4 etc
> > looking forward your update
> > thanks
> 
> no they arent. update your game.
> 
> ![image](https://private-user-images.githubusercontent.com/126014478/314083884-01c56de8-679e-4885-900b-3802b46ceefd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzM5ODMsIm5iZiI6MTcxMDkzMzY4MywicGF0aCI6Ii8xMjYwMTQ0NzgvMzE0MDgzODg0LTAxYzU2ZGU4LTY3OWUtNDg4NS05MDBiLTM4MDJiNDZjZWVmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxMTIxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmQyN2U0N2VkNTY5NDQzOWQzMDczNWIzNzQ3ZTljNTYxMTk1YjFiYWJhMjkxNGZhNGMyOWEwNGE4MDIwMmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fd4hIAKlH2Yy-_7-y92fJs78tYLAG9rMenyFifHn3AQ) ![image](https://private-user-images.githubusercontent.com/126014478/314083977-02474a00-8b79-4f1c-a5c2-1b13564176f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzM5ODMsIm5iZiI6MTcxMDkzMzY4MywicGF0aCI6Ii8xMjYwMTQ0NzgvMzE0MDgzOTc3LTAyNDc0YTAwLThiNzktNGYxYy1hNWMyLTFiMTM1NjQxNzZmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxMTIxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzY1N2IwYTg4N2QwMWQ2ZGM0MzcxYjExNjA2MzAyYjcxMjkyMWFkZGY3Y2VkNWQyMzNjZmEyNWZlZDU2Nzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iNhNjAuYv88o02PV6ggln0yDEEYKE31oxFy-8jGoH7Y)
> 
> > how do i open the garage and autoshow tab it doesnt let me
> 
> launch the aio as admin.

get it, thanks for the help!
