### ISSUE TITLE
The latest version of AIO crashes the game 

### ISSUE THREAD

**Issue by Ponei90** [ForzaMods/Forza-Mods-AIO#123]
### Which version of the app?

1.671.65.0

### Description

After this new version of the game, AIO will cause the game to crash after about 3 to 5 minutes. Also, when I run the tool, the game stutters a lot, causing significant FPS drops.

### Screenshots

![fh5](https://github.com/user-attachments/assets/45a5edd2-032f-4fc1-b5a0-778547cd8ccc)

### Windows version

Windows 10 22H2 (19045)

### Additional context

Maybe you can find a solution for the camera offset also. It's annoying when resets the image. The tools it is working fine, apart from the game crashes.

**Comment by szaaamerik** [comment]
This is a known issue and will be fixed with V3. Closing as duplicate
