### ISSUE TITLE
Game CTD when Forza Mod AIO opens

### ISSUE THREAD

**Issue by KrispyKrisp9000** [ForzaMods/Forza-Mods-AIO#13]
**Describe the bug**
Forza Horizon 5 CTD when Forza Mod AIO is open.

**To Reproduce**
1. Open Forza Horizon 5
2. Open Forza Mod AIO once you've loaded in
3. Get CTD
4. Open FH5 again, this time go into free roam before opening Forza Mod AIO
5. Get CTD 

**Expected behavior**
Game crashes

**Additional context**
Forza Mod AIO exe isn't updated, as it not been uploaded to GitHub yet, though did get the latest update for the rest of the stuff

**Comment by szaaamerik** [comment]
what is ctd?

**Comment by KrispyKrisp9000** [comment]
> what is ctd?

Crash to Desktop

**Comment by szaaamerik** [comment]
> Crash to Desktop



game version?

**Comment by pcconfig01** [comment]
> > Crash to Desktop
> 
> game version?

same problem
ver.  640.062

**Comment by KrispyKrisp9000** [comment]
Latest version of the game on PC is 3.636.732.0, Steam is 1.636.732.0

**Comment by szaaamerik** [comment]
> Latest version of the game on PC is 3.636.732.0, Steam is 1.636.732.0




this is not the latest. update your game

**Comment by The-0mega1** [comment]
Hi, Yeah... I am suffering from this as well, even with the latest version of FH5 and Forza Mods AIO (FMA): 3.640.62.0 and 2.0.8.1 respectively.

**Comment by szaaamerik** [comment]
> Hi, Yeah... I am suffering from this as well, even with the latest version of FH5 and Forza Mods AIO (FMA): 3.640.62.0 and 2.0.8.1 respectively.




you need to download the pre release I posted on this repo.

**Comment by The-0mega1** [comment]
👍

**Comment by KrispyKrisp9000** [comment]
Is the Pre release the main or v2 old, from the drop down menu?
Or am I looking in wrong place?

**Comment by szaaamerik** [comment]
> Is the Pre release the main or v2 old, from the drop down menu? Or am I looking in wrong place?





its neither.

https://github.com/ForzaMods/Forza-Mods-AIO/releases/latest

**Comment by KrispyKrisp9000** [comment]
Thanks, now I can get the new cars again

**Comment by szaaamerik** [comment]
closing since op fixed his issue
