### ISSUE TITLE
FM8 1.559.9113.0 nothing works 

### ISSUE THREAD

**Issue by BeXy808** [ForzaMods/Forza-Mods-AIO#14]
---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

Feature: Bypass
Signature: E8 ? ? ? ? 48 83 C4 ? 5F 5B C3 CC CC CC ? ? ? ? ? ? ? 74 ? ? ? ? ? ? 48

Tool Version: 2.1.0.0
Game: Forza Motorsport 8
Game Version: 1.559.9113.0
Platform: MS

**Comment by szaaamerik** [comment]
maybe if you read my release notes on the discord you'd know
