### ISSUE TITLE
FH5 - Add All Cars feature doesn't work

### ISSUE THREAD

**Issue by DaniG96** [ForzaMods/Forza-Mods-AIO#15]
I tried several times, but nothing. It always crashes the game.

---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

Feature: Sql
Signature: 0F 84 ? ? ? ? 48 8B 35 ? ? ? ? 48 85 F6 74

Tool Version: 2.1.0.0
Game: Forza Horizon 5
Game Version: 1.640.062.0
Platform: OnlineFix - Steam
---------------------------

**Comment by DaniG96** [comment]
With new OnlineFix crack it works, but not the new DLC cars.

**Comment by szaaamerik** [comment]
I guess this issue is resolved as it will not work with dlc cars.
