### ISSUE TITLE
Cheats won't activate - Forza Motorsport

### ISSUE THREAD

**Issue by KrispyKrisp9000** [ForzaMods/Forza-Mods-AIO#16]
**Describe the bug**
Cheats won't activate in Forza Motorsport e.g. Acceleration

**To Reproduce**
1. Open Forza Motorsport and enter practice / race
2. Open Forza Mods AIO and activate the things you need
3. Get error message when try to activate 

**Expected behavior**
Error message pops up, cheat/s say it's on but doesn't work

**Desktop (please complete the following information):**
Error message says:

Feature: Accel
Signature: F3 0F ? ? ? 41 0F ? ? 0F C6 DB ? 41 0F

Tool Version: 2.1.0.0
Game: Forza Motorsport 8
Game Version: 1.559.9113.0
Platform: MS

**Comment by szaaamerik** [comment]
they wont. the mvvm port currently supports only fh5.
