### ISSUE TITLE
Name Spoofer Crashes Game

### ISSUE THREAD

**Issue by procev** [ForzaMods/Forza-Mods-AIO#17]
When I use the Name Spoofer, it freezes game for a second and then the Game crashes

Tool Version: 2.1.0.0
Game: Forza Horizon 5
Game Version: 3.640.62.0
Platform: MS

Thx

**Comment by szaaamerik** [comment]
was this resolved in the latest version?

**Comment by szaaamerik** [comment]
no response. closing
