### ISSUE TITLE
AIO Error (CRACKED VER)

### ISSUE THREAD

**Issue by 4rthem1s** [ForzaMods/Forza-Mods-AIO#18]
**Describe the bug**
AIO error and annoying. That's all I can say.

**To Reproduce**
1. Go to Forza Horizon 5 (Run as admin)
2. Run AIO
3. Click on anyone of the given options, ex; Give all cars, Give credits, etc. But I have discovered that Fly Hack does not give this error, but it doesn't give me the expected Fly Hack ability
4. See AIO error

**Expected behavior**
Expectation: No AIO errors and given what I expect to be given, etc; all cars.

**Screenshots**
![image](https://github.com/ForzaMods/Forza-Mods-AIO/assets/165476724/63a3e24a-cce5-4055-bb54-27f2966d1f4d)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Forza title and version: CRACKED! Forza Horizon 5, Steam, 1.634.818.0

**Additional context**
Once again, I am running on a cracked version and not a legitimate one. I have ran both programs as Administrator and installed Microsoft.NET 8.0, I have all DLC's unlocked including expansion packs

**Comment by szaaamerik** [comment]
update your game. theres no other fix.

**Comment by 4rthem1s** [comment]
used an older version of the AIO, works. thx

**Comment by Lubagit** [comment]
@4rthem1s where did you download it?
