### ISSUE TITLE
Error when trying to toggle the 'make cars free'

### ISSUE THREAD

**Issue by h4xx0r023** [ForzaMods/Forza-Mods-AIO#20]
**Describe the bug**
When running the mod, im getting the following error, when selecting the 'make cars free' option
---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Bypass
Signature: E8 ? ? ? ? 48 83 C4 ? 5F 5B C3 CC CC CC ? ? ? ? ? ? ? 74 ? ? ? ? ? ? 48

Tool Version: 2.1.0.0
Game: Forza Horizon 5
Game Version: 1.480.477.0
Platform: Steam
---------------------------
OK   
---------------------------

**Comment by szaaamerik** [comment]
update your game.
