### ISSUE TITLE
When i used a feature it show me this message

### ISSUE THREAD

**Issue by leonwibu69** [ForzaMods/Forza-Mods-AIO#21]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Forza title and version [e.g. FH5, 1.636.732.0]

**Additional context**

---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Bypass
Signature: E8 ? ? ? ? 48 83 C4 ? 5F 5B C3 CC CC CC ? ? ? ? ? ? ? 74 ? ? ? ? ? ? 48

Tool Version: 2.1.0.0
Game: Forza Horizon 5
Game Version: 1.484.939.0
Platform: Steam
---------------------------
OK   
---------------------------
how to fix this?

**Comment by szaaamerik** [comment]
update your game.

**Comment by leonwibu69** [comment]
> update your game.

I used crack so what version of the aio can I use?
