### ISSUE TITLE
what version did i need for cracked forza with version of 1.484.939.0

### ISSUE THREAD

**Issue by leonwibu69** [ForzaMods/Forza-Mods-AIO#23]
So i download the crack from fitgirl and the version is 1.484.939.0
 wht version of aio can i use?

**Comment by XandarNull** [comment]
in the cheat it says "platform: steam" i wish there was a way to change that to a cracked game exe, i'm guessing the devs haven't implemented it yet

**Comment by szaaamerik** [comment]
> in the cheat it says "platform: steam" i wish there was a way to change that to a cracked game exe, i'm guessing the devs haven't implemented it yet




we only have detection for online fix cracks and its just a visual thing as it doesn't change anything in the code execution.

**Comment by szaaamerik** [comment]
ok, there is nothing I can do apart from telling you to update the game. closing with the wontfix label because I don't plan on supporting ancient game versions.
