### ISSUE TITLE
Display all cars doesn't work in FH4

### ISSUE THREAD

**Issue by h2o-OgUrEz** [ForzaMods/Forza-Mods-AIO#24]
---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Sql
Signature: 0F 84 ? ? ? ? 48 8B 35 ? ? ? ? 48 85 F6 74

Tool Version: 2.1.0.0
Game: Forza Horizon 4
Game Version: 1.478.564.0
Platform: Steam
---------------------------
OK   
---------------------------

**Comment by szaaamerik** [comment]
you haven't read my announcement. 

![image](https://github.com/ForzaMods/Forza-Mods-AIO/assets/126014478/d4e214bf-93a5-4600-b38e-b514fa5952a7)


invalid issue.
