### ISSUE TITLE
FM8 Forza Mods AIO - Error

### ISSUE THREAD

**Issue by KB4332** [ForzaMods/Forza-Mods-AIO#25]
---------------------------
Forza Mods AIO - Error
---------------------------
Trying to use the AIO to quick add all cars and it just keeps giving me the same error message after rebooting game and the AIO

Tool Version: 2.1.0.0
Game: Forza Motorsport 8
Game Version: 1.559.9113.0
Platform: MS

**Comment by szaaamerik** [comment]
invalid issue. fh4 and fm8 aren't supported in the latest version as it was almost a full rewrite
