### ISSUE TITLE
Does the menu work with microsoft version

### ISSUE THREAD

**Issue by ShadyDrifter** [ForzaMods/Forza-Mods-AIO#27]
i tried to use the menu with Microsoft version and the menu crashes when i try to use it, and it doesn't hook properly

**Comment by ShadyDrifter** [comment]
i tried to use the menu with Microsoft version and the menu crashes when i try to use it, and it doesn't hook properly

**Comment by szaaamerik** [comment]
not enough info. not helping if you just ignore the fucking bug template
