### ISSUE TITLE
Cheats Are not working

### ISSUE THREAD

**Issue by Nilesh5199** [ForzaMods/Forza-Mods-AIO#28]
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and
the tool.
If this error still occurs, please (Press Ctrl+C) to copy, and make an
issue on the github repository or post the copied text on the aio
mega-thread in our discord server (discord.ggfforzamods).
Feature: Bypass
Signature: E8 ? ? ? ? 48 83 C4 ? 5F 5B C3 CC CC CC ? ? ? ? ? ? ? 74 ? ?
![Screenshot 2024-04-12 165815](https://github.com/ForzaMods/Forza-Mods-AIO/assets/105578345/441e32a7-458f-4360-b4bd-cdc74c5cca8f)

48
Tool Version: 2.1 .O.O
Game: Forza Horizon 5
Game Version: 1.573.834.0
Platform: Steam

**Comment by szaaamerik** [comment]
update your game, no other way.
