### ISSUE TITLE
cannot use in FH4

### ISSUE THREAD

**Issue by sT-Ar11** [ForzaMods/Forza-Mods-AIO#29]
---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Sql
Signature: 0F 84 ? ? ? ? 48 8B 35 ? ? ? ? 48 85 F6 74

Tool Version: 2.1.0.0
Game: Forza Horizon 4
Game Version: 1.478.564.0
Platform: Steam

**Comment by szaaamerik** [comment]
this is a known issue, it will be resolved with a new update.

**Comment by szaaamerik** [comment]
fixed with the latest update. SQL should work now
