### ISSUE TITLE
Mods Not Working Since Upgrade

### ISSUE THREAD

**Issue by jw0727** [ForzaMods/Forza-Mods-AIO#30]
Since upgrading to new game version on 04/23/2024, none of the features in the mod tool are functioning.

---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Bypass
Signature: E8 ? ? ? ? 48 83 C4 ? 5F 5B C3 CC CC CC ? ? ? ? ? ? ? 74 ? ? ? ? ? ? 48

Tool Version: 2.1.0.0
Game: Forza Horizon 5
Game Version: 3.642.644.0
Platform: MS

1. Attempt to change any setting

Screenshot:
![image](https://github.com/ForzaMods/Forza-Mods-AIO/assets/167912123/d7801013-5601-40fa-9016-0912a8552b56)

**Comment by szaaamerik** [comment]
addressed on discord.
