### ISSUE TITLE
New update messed up the menu

### ISSUE THREAD

**Issue by iduahjksdge** [ForzaMods/Forza-Mods-AIO#31]
**Describe the bug**

**To Reproduce**
1. Click on any mod that isn't apart of the "Autoshow/Garages" section
2. Click on the on or off button
3. Scroll down past "Autoshow/Garages" section 
4. See error: Says "feature bypass" and then some random letters and numbers

**Expected behavior**
Every time I try to use any other mod that isn't apart of Autoshow/Garages section, it gives me that very same error
**Screenshots**
![Screenshot 2024-04-23 175224](https://github.com/ForzaMods/Forza-Mods-AIO/assets/60082965/bb1b9cf5-a953-4379-9f39-f7fecae14624)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Forza title and version  FH5, 3.642.644.0

 - AIO version 2.1.0.0

**Additional context**

**Comment by thepala01** [comment]
![Ekran görüntüsü 2024-04-24 011652](https://github.com/ForzaMods/Forza-Mods-AIO/assets/167926537/5ee306a7-187b-49b3-b970-f5dd6d3905e6)
I will get the same error, how can I solve it?

**Comment by thepala01** [comment]
![Ekran görüntüsü 2024-04-24 011652](https://github.com/ForzaMods/Forza-Mods-AIO/assets/167926537/53be7086-7bd8-49aa-85a3-fe9125df4c70)
I'm getting the same error, how can I solve it?

**Comment by ItzDj121** [comment]
![image](https://github.com/ForzaMods/Forza-Mods-AIO/assets/168033990/dfc7bc39-0518-4d09-994f-7ff7bc292430) 
Please help i dont understand what caused this if its me or something else

**Comment by TomerGamerTV** [comment]
---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Bypass
Signature: E8 ? ? ? ? 48 83 C4 ? 5F 5B C3 CC CC CC ? ? ? ? ? ? ? 74 ? ? ? ? ? ? 48

Tool Version: 2.1.0.0
Game: Forza Horizon 5
Game Version: 3.642.644.0
Platform: MS
---------------------------
OK   
---------------------------

**Comment by szaaamerik** [comment]
- I've updated the AIO so this is now an irrelevant question because this was resolved
