### ISSUE TITLE
Freeze AI Crashes Game

### ISSUE THREAD

**Issue by gorlinvongz** [ForzaMods/Forza-Mods-AIO#35]
**Describe the bug**
Freeze AI Crashes Game

 - OS: [Windows 11]
 - Forza title and version [FH5, 1.642.644.0]
 - AIO version [2.2.0.0]

THX

**Comment by szaaamerik** [comment]
not enough info, how to reproduce?
waiting on repsonse.

**Comment by szaaamerik** [comment]
I am not able to reproduce this bug with just toggling the switch as well.

**Comment by szaaamerik** [comment]
no response, closing
