### ISSUE TITLE
 I cant use this in FH4  

### ISSUE THREAD

**Issue by V50tt0** [ForzaMods/Forza-Mods-AIO#37]
**---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Accel
Signature: F3 0F ? ? ? 41 0F ? ? 0F C6 DB ? 41 0F

Tool Version: 2.2.0.0
Game: Forza Horizon 4
Game Version: 1.478.564.0
Platform: Steam
---------------------------
确定   
---------------------------
**
self/vehicle
acceleration

**Comment by szaaamerik** [comment]
as we said, fh4 is partially supported and not everything works. closing this as an invalid issue
