### ISSUE TITLE
how come the add all cars option only adds 700 cars instead of 800 like the amount in the game because it worked last time 

### ISSUE THREAD

**Issue by somethingwrongwe** [ForzaMods/Forza-Mods-AIO#40]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Forza title and version [e.g. FH5, 1.636.732.0]
 - AIO version [e.g. 2.1.0.0]

**Additional context**

**Comment by szaaamerik** [comment]
it's because it was changed to work with people that don't have vip/carpass. this is not going to be fixed

**Comment by somethingwrongwe** [comment]
what if you have carpass and vip
