### ISSUE TITLE
Camera offset bug

### ISSUE THREAD

**Issue by Ponei90** [ForzaMods/Forza-Mods-AIO#43]
**Describe the bug**
When using camera offset (cockpit, or outside the cockpit), the image goes up and down. 
Try to drive around 1 or 2 minutes, using the camera offset, then you will see how the camera goes up and down

Desktop 
 - OS: Windows 10 Pro 22H2
 - Forza title and version FH5, 1.642.644.0
 - AIO version  2.2.0.0

**Additional context**

**Comment by szaaamerik** [comment]
it's not a bug. 
every function reverts its hooks for a certain amount of time to bypass the anticheat
