### ISSUE TITLE
Velocity,wheelspeed,super brake these three options fail

### ISSUE THREAD

**Issue by ZHANG66862** [ForzaMods/Forza-Mods-AIO#44]
Version 2.2
First enter the game, then open the aio tool, open options and set hotkeys, then go to drive, they do not work. I have tried my computer at home and the computer in the Internet cafe, but they don't work.
![IMG_20240430_183536](https://github.com/ForzaMods/Forza-Mods-AIO/assets/168536685/a59af501-fbe0-43ee-bb1f-6b2d6952d999)
![IMG_20240430_183536](https://github.com/ForzaMods/Forza-Mods-AIO/assets/168536685/8dd6b3cb-e17a-4e5d-9ddf-2007a0c745a7)

**Comment by ZHANG66862** [comment]
![Uploading IMG_20240430_183536.jpg…]()

**Comment by szaaamerik** [comment]
you don't just press the hotkey if you do it that way, you hold it.

**Comment by Kazbek205** [comment]
how to bind it to a gamepad? I don't play with a keyboard

**Comment by szaaamerik** [comment]
Closing as not planned because of 0 response from the issue maker
