### ISSUE TITLE
Camera cockpit goes up and down / coolshit "unlock clothes"

### ISSUE THREAD

**Issue by Ponei90** [ForzaMods/Forza-Mods-AIO#47]
**Is your feature request related to a problem? Please describe.**
Could you make the camera as previous version? To not go up and down when using camera offset? 
Also can you bring back the "unlock clothes" option?

**Comment by szaaamerik** [comment]
it won't be fixed as that's part of the bypass.
no, I won't bring it back. it didn't even work
