### ISSUE TITLE
Manual time gets overridden by game?

### ISSUE THREAD

**Issue by curlily** [ForzaMods/Forza-Mods-AIO#48]
When setting a manual time under environment tweaks, it works for a bit but after some time the real time overrides the manual time for a second, then the mod applies the manual time again. 
Happens like every 30 seconds.
Very noticable when the lobby is daytime and the manual time is set to night.

 - OS: Windows 11
 - Forza Horizon 5, MS, 3.642.644.0
 - AIO version: 2.2.0.0

**Comment by szaaamerik** [comment]
nah this is just a part of the bypass.
every hook gets reverted every 25s to bypass the crc checks and other anticheat functions
