### ISSUE TITLE
Dear author, I hope to add the function of input code to add specified vehicles, in addition to the function of deleting duplicate vehicles in the garage, because it is very tedious to remove them one by one

### ISSUE THREAD

**Issue by xqcssp** [ForzaMods/Forza-Mods-AIO#49]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by szaaamerik** [comment]
need more info.
I do not understand what do you mean

**Comment by szaaamerik** [comment]
this is a stale issue.
I'll be closing it
