### ISSUE TITLE
добавьте чтобы можно было скорость использовать через джойстик ,получается только клавишу клавиатуры поставить

### ISSUE THREAD

**Issue by Kazbek205** [ForzaMods/Forza-Mods-AIO#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by szaaamerik** [comment]
I can't understand this. 
Write in English or I'm banning you off the repo

**Comment by szaaamerik** [comment]
Closing as no response
