### ISSUE TITLE
Hello:) I wanted to inform that the newest version as of today (2024-05-21) is regarded as a virus by windows. 

### ISSUE THREAD

**Issue by StorShlong69** [ForzaMods/Forza-Mods-AIO#52]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Forza title and version [e.g. FH5, 1.636.732.0]
 - AIO version [e.g. 2.1.0.0]

**Additional context**

**Comment by szaaamerik** [comment]
it's not a virus and you can fully read its source. 
I'm not sending executables to Microsoft so I'm gonna close this as not planned
