### ISSUE TITLE
Some stuff is not working while racing

### ISSUE THREAD

**Issue by TomerGamerTV** [ForzaMods/Forza-Mods-AIO#59]
**Describe the bug**
Things in the handling section stop working when starting a race, if i set stuff like velocity and acceleration in the menu before the race starts it works but the second i start it everything just seems to stop working (the toggles are still turned on) and when finishing the race it starts working again
**To Reproduce**
1. Turn any setting in handling on and change some stuff
2. Get into a race
3. Start the race

**Expected behavior**
Work normally like before
**Screenshots**
![image](https://github.com/ForzaMods/Forza-Mods-AIO/assets/44266242/6f6b3b9b-bd21-4297-aa97-8c9c29d4e152)

**Desktop (please complete the following information):**
 - OS: Windows 11
 -  FH5, 3.646.267.0
 - AIO version 2.3.0.0

**Comment by szaaamerik** [comment]
this is intentional to stop speedhackers from ruining online activities.
this will not be fixed and I am closing this issue as not planned

**Comment by TomerGamerTV** [comment]
> this is intentional to stop speedhackers from ruining online activities. this will not be fixed and I am closing this issue as not planned

Can you show me where is the check in the code? idc about the online activities I'm playing solo.

**Comment by szaaamerik** [comment]
I'm sorry but I am not providing any information on how to reenable the functionality because I don't want the speedhackers seeing it. You can find the check very easily though

**Comment by TomerGamerTV** [comment]
And what if you added a check to see if the user is playing solo and then
let him use it?

**Comment by szaaamerik** [comment]
until someone does it for me or playground responds to my message, I'm not doing it.

**Comment by TomerGamerTV** [comment]
What do you need from playground

**Comment by szaaamerik** [comment]
CRaceInfo
