### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by qRayzenx** [ForzaMods/Forza-Mods-AIO#61]
### Which version of the app?

Fh4

### Description

taking this error

### Screenshots

![Ekran görüntüsü 2024-05-26 214156](https://github.com/ForzaMods/Forza-Mods-AIO/assets/170888080/5637526c-a735-41e9-904a-b873f0dff60c)

### Windows version

Windows 10 22H2 (19045)

**Comment by szaaamerik** [comment]
this issue is very invalid, fill it out properly or I'm closing it
