### ISSUE TITLE
Bring back original turn assist 

### ISSUE THREAD

**Issue by p-xe** [ForzaMods/Forza-Mods-AIO#65]
### Description

the current steering options is just really weird and it just isn’t as good as the previous turn assist where it gripped the road and like had a really fast turning speed

### Screenshots

N/A

### Windows version

Windows 10 22H2 (19045)

### Additional context

N/A

**Comment by szaaamerik** [comment]
there are no plans to restore the legacy handling page.
I will close this as not planned

**Comment by p-xe** [comment]
why not design it to ur own gui library or whatever then?  bro plz previous turn assist was so good

**Comment by p-xe** [comment]
or like re work the steering shit or something idk why u don’t wanna bring back a better version of what u currently have

**Comment by szaaamerik** [comment]
listen man this is not about UI/UX.
It's about how features work now, they've completely changed since the legacy V2 times

**Comment by p-xe** [comment]
so like ur basically saying the way u did it previously doesn’t work as well anymore? and now it’s completely different

**Comment by szaaamerik** [comment]
no I'm saying I've got much better ways of executing features than before, and that turn assist sadly can't be brought back to the new codebase

**Comment by p-xe** [comment]
aw i see okay well one thing about the steering options is that i always
have to go to settings and re save my assistance settings for it to apply,
is it supposed to work like that?

**Comment by szaaamerik** [comment]
>"have to go to settings and re save my assistance settings for it to apply,"

huh? there is no save button or anything in the AIO?

**Comment by p-xe** [comment]
nah , i just change up the velocity and shit and apply it by going to forza
settings and re saving my assistance

**Comment by szaaamerik** [comment]
I can't understand what you're saying

**Comment by p-xe** [comment]
alright i’ll make a video when i wake up cause i can’t explain it well
either

**Comment by p-xe** [comment]
> I can't understand what you're saying

https://streamable.com/xcj6kp

look at the front wheel after i apply changes

**Comment by szaaamerik** [comment]
yes, it is supposed to work like that. these changes do not apply until you swap a setting in the game, this is typical memory edit.

**Comment by p-xe** [comment]
ohhh okay
