### ISSUE TITLE
Editing Top Speed

### ISSUE THREAD

**Issue by TheGreenBandit** [ForzaMods/Forza-Mods-AIO#66]
### Description

There should be an option for us to edit our top speed, this way we can troll with slow cars, could probably be done by just setting our velocity.

### Screenshots

nonaplicabble

### Additional context

how yall get sigs, figure out names for classes etc, any videos yall recommend?

**Comment by szaaamerik** [comment]
the 720km/h limit is const and I doubt we can change it.

regarding your second question, we don't figure out class names. for sigs, I have a plug-in that automatically does it for me. I don't have any videos

**Comment by TheGreenBandit** [comment]
> the 720km/h limit is const and I doubt we can change it.
> 
> regarding your second question, we don't figure out class names. for sigs, I have a plug-in that automatically does it for me. I don't have any videos 

No i mean not updating the current ones, i mean finding what you want to sig, also for the limit i meant for individual cars, as for example with a certain tune a car could have a top speed of 120mph while with another it could have a speed of 150mph, the max could be 720kmh then or 447mph

**Comment by szaaamerik** [comment]
through reverse engineering. you can "increase" the top speed by using velocity or/and wheelspeed.

**Comment by TheGreenBandit** [comment]
> through reverse engineering. you can "increase" the top speed by using velocity or/and wheelspeed.

? So how would you find the sig for the velocity or wheelspeed? Just use cheat engine, change tune, search for increased / decreased value off of a new tune? But then how do u sig things like movement?

**Comment by szaaamerik** [comment]
there's no sig for velocity nor wheelspeed. I'm not explaining the techniques of what and how do I reverse stuff because I'm not comfortable with it
