### ISSUE TITLE
我们无法在车辆收藏中购买车辆

### ISSUE THREAD

**Issue by 6KKK6** [ForzaMods/Forza-Mods-AIO#68]
### Which version of the app?

最新版本

### Description

有一部分车辆无法购买

### Screenshots

![IMG_20240608_223230](https://github.com/ForzaMods/Forza-Mods-AIO/assets/128572343/62868079-c110-4a41-a477-79ad9e74c834)

### Windows version

Windows 11 23H2 (22631)

### Additional context

我相信你一定能修复这些bug

**Comment by szaaamerik** [comment]
this is DLC cracking.
this will not be "fixed", you need to buy the dlc.
I'll close this issue as not plannee
