### ISSUE TITLE
 Address for this feature wasn't found! 

### ISSUE THREAD

**Issue by zwendry** [ForzaMods/Forza-Mods-AIO#69]
### Which version of the app?

Tool Version: 2.3.0.0 

### Description

---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Bypass
Signature: 49 8B ? FF 50 ? 48 8D ? ? ? ? ? FF 15 ? ? ? ? 8B 8D

Tool Version: 2.3.0.0
Game: Forza Horizon 5
Game Version: 1.484.939.0
Platform: Steam
---------------------------
OK   
---------------------------

### Screenshots

![Screenshot 2024-06-12 201927](https://github.com/ForzaMods/Forza-Mods-AIO/assets/172535609/c33e0f51-cec7-4142-960b-8a8b2b93696f)

### Windows version

Windows 11 24H2 (26052)

**Comment by szaaamerik** [comment]
update your game.
I don't plan on supporting old versions in new releases
