### ISSUE TITLE
如果刷超级抽奖会被封号吗？

### ISSUE THREAD

**Issue by Vee99s** [ForzaMods/Forza-Mods-AIO#70]
### Which version of the app?

最新

### Description

会吗？会吗？

### Screenshots

无

### Windows version

Windows 11 24H2 (26052)

**Comment by szaaamerik** [comment]
I can't understand this even with a translator. please rewrite this in english

**Comment by Vee99s** [comment]
> I can't understand this even with a translator. please rewrite this in english

Will I be banned if I run a wheelspins online？

**Comment by szaaamerik** [comment]
possibly
