### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by Rudepllayer** [ForzaMods/Forza-Mods-AIO#71]
### Which version of the app?

2.3.0.0

### Description

I have the cracked version of forza horizon 5 and when i use the modmenu to add money, when i press to turn it on i gives me an error. Also when i try to use all of the autoshow otions it crashes the game.

### Screenshots

![imagem_2024-06-14_193924162](https://github.com/ForzaMods/Forza-Mods-AIO/assets/172845552/30c0ee9a-2bb3-4c71-84a5-123ba535a55b)
this is the error that gives when i turn on the add money option

### Windows version

Windows 11 23H2 (22631)

**Comment by szaaamerik** [comment]
update your game. no other solution. also "app version" does not mean your game version, you need to learn to read.
