### ISSUE TITLE
Forza updated today 

### ISSUE THREAD

**Issue by auslee43** [ForzaMods/Forza-Mods-AIO#73]
### Which version of the app?

2.3.00

### Description

Forza updated today making the menu invalid & it will not run any mods

### Screenshots

Menu needs updated to be compatible with Forza update 

### Windows version

Windows 11 24H2 (26052)

**Comment by szaaamerik** [comment]
I mentioned this on the forza mods discord server already, I'm not updating the aio until I come back from holiday
