### ISSUE TITLE
An Unexpected Error // Cant run the mod

### ISSUE THREAD

**Issue by LilOkiex** [ForzaMods/Forza-Mods-AIO#74]
### Which version of the app?

2.3.0.0

### Description

---------------------------
Forza Mods AIO - Error
---------------------------
An unexpected error happened.
Please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods)

Source:Application.Current.DispatcherUnhandledException
Exception:Invalid class 
Exception Source:System.Management

Tool Version: 2.3.0.0
Game: Forza Horizon 5
Game Version: 3.649.948.0
Platform: MS
---------------------------
OK   
---------------------------

### Screenshots

![image](https://github.com/ForzaMods/Forza-Mods-AIO/assets/80932419/070f4720-406a-4a81-baab-361d3c93f991)
![image](https://github.com/ForzaMods/Forza-Mods-AIO/assets/80932419/ad1badad-1e4c-49ac-97f8-49543faa7d63)

### Windows version

Windows 11 21H2 (22000)

### Additional context

I just reinstalled the newer version after not using it for awhile ! Everytime I try to use something another error pops up (Screenshot above)

**Comment by vmred** [comment]
I suppose requires update itself as forza version was recently bumped. Same as before after forza update.

**Comment by V50tt0** [comment]
we need new update please

**Comment by szaaamerik** [comment]
> we need new update please



stop fucking asking, it's annoying. I've already mentioned that I am on holiday and there are no other maintainers

**Comment by dimuska139** [comment]
@szaaamerik hello! Is it completed? I've downloaded the last (today) release 2.4.0.1 but it is not working
<img width="312" alt="image_2024-07-23_00-08-00" src="https://github.com/user-attachments/assets/e01fe7bd-fa9f-4295-908e-1ab984865724">

Or did you only fix the MS version?

**Comment by szaaamerik** [comment]
this feature wasn't ported to fh4 just yet. it is under the radar, though just very low priority

**Comment by dimuska139** [comment]
Other features won't work too...
