### ISSUE TITLE
Bug title，Request an update，Unexpected errors

### ISSUE THREAD

**Issue by CHINA123455** [ForzaMods/Forza-Mods-AIO#78]
### Which version of the app?

2.3.00

### Description

Forza Mods AIO -Request an  update
Forza Mods AIO  lapse
Tool version: 2.3.0.0
Game: Forza Horizon 5
Game Version:Ver.649.948
Platform:PC
Thanks

### Screenshots

![微信图片_20240622120236](https://github.com/ForzaMods/Forza-Mods-AIO/assets/173522043/9f7e5955-4ec0-426b-abf2-d32f0c2e5660)
![微信图片_20240622120241](https://github.com/ForzaMods/Forza-Mods-AIO/assets/173522043/410b426f-dd9a-40fd-9d3d-2f88957d342d)

### Windows version

Windows 11 22H2 (22621)

### Additional context

Display all cars No response when opened  and the issue in the screenshot above arises.
We need a new version, thanks

**Comment by szaaamerik** [comment]
this one is an issue with the Chinese github api or something, I will not be able to reproduce

**Comment by CHINA123455** [comment]
> 这个是中文github api什么的，我无法重现

ok,thanks
