### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by Ghost-Reborn** [ForzaMods/Forza-Mods-AIO#79]
### Which version of the app?

2.3.0.0

### Description

---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Local Player Hook
Signature: F3 0F ? ? ? 49 8B ? 49 8B ? 0F 28

Tool Version: 2.3.0.0
Game: Forza Horizon 5
Game Version: 1.405.002.0
Platform: Steam
---------------------------
OK   
---------------------------

### Screenshots

![Screenshot (1)](https://github.com/ForzaMods/Forza-Mods-AIO/assets/46274430/04daf348-f94a-4048-a9c1-35d2e74b3520)

### Windows version

Windows 11 23H2 (22631)

**Comment by szaaamerik** [comment]
your game version is too old. soon to be a three-year out of date anniversary, update it else it won't work
