### ISSUE TITLE
forza mods aio

### ISSUE THREAD

**Issue by spidernit** [ForzaMods/Forza-Mods-AIO#80]
### Which version of the app?

forza mods aioTool Version: 2.3.0.0 Game: Forza Horizon 5 Game Version: 1.649.948.0 Platform: Steam

### Description

when I turn on the acceleration it happens

### Screenshots

---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Bypass
Signature: 49 8B ? FF 50 ? 48 8D ? ? ? ? ? FF 15 ? ? ? ? 8B 8D

Tool Version: 2.3.0.0
Game: Forza Horizon 5
Game Version: 1.649.948.0
Platform: Steam
---------------------------
OK   
---------------------------

### Windows version

Windows 10 22H2 (19045)

**Comment by szaaamerik** [comment]
addressed many times on discord, not fixing until I come back from holiday
