### ISSUE TITLE
crash game or mod when toggle any on off switch

### ISSUE THREAD

**Issue by ErdemOzbaykus** [ForzaMods/Forza-Mods-AIO#81]
### Which version of the app?

2.3.0.0

### Description

when ı try to use any on off switch it getting gray color and locked  a few second later getting crashed or game crashed

### Screenshots

![resim_2024-06-23_134949424](https://github.com/ForzaMods/Forza-Mods-AIO/assets/53942987/57027d04-1566-44f3-9a42-5c24ab519539)

### Windows version

Windows 11 23H2 (22631)

**Comment by vmred** [comment]
The same as here: https://github.com/ForzaMods/Forza-Mods-AIO/issues/74

mod tool requires update, as replied from one of developers need to wait for it.

**Comment by szaaamerik** [comment]
closing because duplicate
