### ISSUE TITLE
1.649.948.0

### ISSUE THREAD

**Issue by GodNev3r1212** [ForzaMods/Forza-Mods-AIO#83]
### Which version of the app?

Fail to run the mod

### Description

---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Bypass
Signature: 49 8B ? FF 50 ? 48 8D ? ? ? ? ? FF 15 ? ? ? ? 8B 8D

Tool Version: 2.3.0.0
Game: Forza Horizon 5
Game Version: 1.649.948.0
Platform: Steam
---------------------------
OK   
---------------------------

### Screenshots

![Screenshot 2024-06-24 131557](https://github.com/ForzaMods/Forza-Mods-AIO/assets/119688867/6086d6c7-edaf-447c-8241-4778f3ec8ae5)

### Windows version

Windows 11 23H2 (22631)

**Comment by szaaamerik** [comment]
![Screenshot_20240624_184009_Discord.jpg](https://media.discordapp.net/attachments/1106332887973892207/1127225115684376656/zablotony.gif?ex=667ac1b2&is=66797032&hm=cce2dbe76bfc4381f3ba453d33182f7a7fa03e2a4bf0d32a75b8f7781d76286c&)
