### ISSUE TITLE
無料の衣類と、金、xpを追加する機能が使えない。エラーが発生する。

### ISSUE THREAD

**Issue by F150mark2** [ForzaMods/Forza-Mods-AIO#84]
### Which version of
  new

### Description

無料の車は機能するが、無料衣類と金、xpなどが機能せず、エラーが発生します。 修正する必要がある。

### Screenshots

/
![{5436608B-B4FD-4372-B04B-F9FBD48C81F8} png](https://github.com/ForzaMods/Forza-Mods-AIO/assets/173690586/c0297aa5-d835-4d7d-a59f-6276ea837156)

### Windows version

1903 Windows10

**Comment by vmred** [comment]
same as https://github.com/ForzaMods/Forza-Mods-AIO/issues/74
