### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by Aculpro** [ForzaMods/Forza-Mods-AIO#85]
### Which version of the app?

Tool Version: 2.3.0.0, Game Version: 3.649.948.0

### Description

I was trying to have fun with the acceleration but as soon as I turned it on this comes up(Screenshot down below) I don't know what to do and tried everything that it told me to do. Please help me.

### Screenshots

![Forza](https://github.com/ForzaMods/Forza-Mods-AIO/assets/173703377/9afbaeb5-f52a-4b2d-a6c9-d0f28ca27ce8)

### Windows version

Windows 10 22H2 (19045)

### Additional context

---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Bypass
Signature: 49 8B ? FF 50 ? 48 8D ? ? ? ? ? FF 15 ? ? ? ? 8B 8D

Tool Version: 2.3.0.0
Game: Forza Horizon 5
Game Version: 3.649.948.0
Platform: MS

**Comment by vmred** [comment]
same as https://github.com/ForzaMods/Forza-Mods-AIO/issues/74
