### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by TaLESue** [ForzaMods/Forza-Mods-AIO#88]
### Which version of the app?

2.3.0.0

### Description

vFH4 and FH5, manipulation and tuning are not available

### Screenshots

<img width="601" alt="微信图片_20240701205937" src="https://github.com/ForzaMods/Forza-Mods-AIO/assets/174342563/74938646-eb60-4935-88ea-c41ffb87d0b7">

### Windows version

Windows 11 23H2 (22631)

**Comment by JimmyFlo** [comment]
same thing here

**Comment by hooke007** [comment]
https://github.com/ForzaMods/Forza-Mods-AIO/issues/74

**Comment by EP1PHANEIA** [comment]
bro在度假

**Comment by szaaamerik** [comment]
duplicate of #74
