### ISSUE TITLE
YOU STEWPID NEGGAR

### ISSUE THREAD

**Issue by negarzsuckmadik** [ForzaMods/Forza-Mods-AIO#96]
### Description

Fxck your mood, give us the newest one you selfish degenerate prixck. Fxxck your ego in discord, R3tarded sh/thole.

### Screenshots

Your discord mods suxk btw, Server davs sxck ma dik!

**Comment by szaaamerik** [comment]
you can punch sand, I'm not fixing shit. who are you to tell me what to do? you're the retarded one. you're nothing and you will never be anything. you're just a useless piece of shit that contributed nothing to the aio yet you demand it. you should have been a wank.   you're just a narrow-minded, ignorant fat retard who thinks they are entitled to everything. newsflash, you aren't.

**Comment by negarzsuckmadik** [comment]
Haha cry over it, I bet you're just an incel who tries to fulfill his ego
with harassing people on discord. Slave.

13 Tem 2024 Cmt 12:29 tarihinde merika ***@***.***> şunu
yazdı:

**Comment by szaaamerik** [comment]
I'm not going to cry over some brain-dead faggot coon, again you can go suck dick. you are useless

**Comment by negarzsuckmadik** [comment]
A slave says you are useless. Now that's funny you nigger, go get some
bitches instead of being a discord incel and lose some fat.

13 Tem 2024 Cmt 13:26 tarihinde merika ***@***.***> şunu
yazdı:
