### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kilsaz** [ForzaMods/Forza-Mods-AIO#97]
### Which version of the app?

2.3.0.0

### Description

I press "UNLOCK" and enter a number and turn it on and it shows me the error.

### Screenshots

![Screenshot 2024-07-16 134842](https://github.com/user-attachments/assets/b32b4cef-f546-44e6-a9d1-1edbe79892a4)

### Windows version

Windows 11 23H2 (22631)

**Comment by bigskip95** [comment]
I get the same error! Hopefully the devs can help

**Comment by FunnyWii** [comment]
> I get the same error! Hopefully the devs can help

The maintainer is under vacation and there is no other maintainers, so what we can do is waiting

**Comment by vmred** [comment]
same as https://github.com/ForzaMods/Forza-Mods-AIO/issues/74

**Comment by szaaamerik** [comment]
duplicate
