### ISSUE TITLE
fh5 crashes 

### ISSUE THREAD

**Issue by mirza-OP** [ForzaMods/Forza-Mods-AIO#98]
### Which version of the app?

v2.8

### Description

fh5 is crashes when aio is opened

### Screenshots

![Capture](https://github.com/user-attachments/assets/1779b574-a36a-4733-beac-e7d68e33d6ca)

### Windows version

Windows 10 22H2 (19045)

### Additional context

If I use v2.3 this error occurs 
![Capture](https://github.com/user-attachments/assets/8d3539e0-fca1-4d9d-88a6-7318981d1d08)

**Comment by Schlappenschleuder** [comment]
Compare youre FH5 version with the latest patch, you will notice it's outdated.
I suggest you to join their discord. There will be a new release soon but we need to be patient but if it goes online you will see it in their accouncements.

**Comment by vmred** [comment]
same as https://github.com/ForzaMods/Forza-Mods-AIO/issues/74

**Comment by szaaamerik** [comment]
duplicate
