### ISSUE TITLE
Forza crashes very often

### ISSUE THREAD

**Issue by 361m** [ForzaMods/Forza-Mods-AIO#99]
### Which version of the app?

2.4.0.0

### Description

Everytime after around 10-20 minutes of just driving around w the aio open, if i have pretty much anything toggled, forza just crashes without any error from aio or forza.

### Screenshots

cannot send a screenshot

### Windows version

Windows 11 21H2 (22000)

**Comment by yxfyyds** [comment]
Author,Hello,AIOAfter using it for 10 minutes,The game will freeze until it crashes,Bring a not very good game experience,I hope to optimize the update

**Comment by yxfyyds** [comment]
Using AIO to modify any function, playing the game in the following minutes will cause the screen to freeze until it crashes, but AIO will not report any form of error.

**Comment by yxfyyds** [comment]
Boss, can you understand my breakdown? After playing AIO, halfway through the game, it crashed and crashed, which was really uncomfortable

**Comment by yxfyyds** [comment]
What's going on here? After opening AIO, the game crashed in less than 2 minutes.
![Uploading 7b4d3488c677b41d5299c23893f5e8f6.png…]()

**Comment by yxfyyds** [comment]
![Uploading 7b4d3488c677b41d5299c23893f5e8f6.png…]()

**Comment by VMargreiter** [comment]
@yxfyyds As this is a free and open source project, have you considered debugging your issues further and working on a solution instead of trying to push the kind soul that has made this available to us after other solutions already failed / have been taken down?

**Comment by szaaamerik** [comment]
should be fixed with the hotfix.
